// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHVWgJ5gufB1P_Mf-JgNUgaHR1dj0jUg',
    appId: '1:282925026552:web:8f91980307fe4554e83f0d',
    messagingSenderId: '282925026552',
    projectId: 'chatapp-92b4a',
    authDomain: 'chatapp-92b4a.firebaseapp.com',
    storageBucket: 'chatapp-92b4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA050IbPGn3Dn9MzijX_4sf8muelIBUgLU',
    appId: '1:282925026552:android:eadc86d7101b54bae83f0d',
    messagingSenderId: '282925026552',
    projectId: 'chatapp-92b4a',
    storageBucket: 'chatapp-92b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNE-wKrBlki0doh7fngsBqkWKE9-s0Qys',
    appId: '1:282925026552:ios:d1f89d896e7c57f1e83f0d',
    messagingSenderId: '282925026552',
    projectId: 'chatapp-92b4a',
    storageBucket: 'chatapp-92b4a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNE-wKrBlki0doh7fngsBqkWKE9-s0Qys',
    appId: '1:282925026552:ios:d1f89d896e7c57f1e83f0d',
    messagingSenderId: '282925026552',
    projectId: 'chatapp-92b4a',
    storageBucket: 'chatapp-92b4a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxHVWgJ5gufB1P_Mf-JgNUgaHR1dj0jUg',
    appId: '1:282925026552:web:6b55b6945e71e417e83f0d',
    messagingSenderId: '282925026552',
    projectId: 'chatapp-92b4a',
    authDomain: 'chatapp-92b4a.firebaseapp.com',
    storageBucket: 'chatapp-92b4a.firebasestorage.app',
  );
}
